-- MySQL Script generated by MySQL Workbench
-- Mon Aug 29 08:38:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema neoness
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `neoness` ;

-- -----------------------------------------------------
-- Schema neoness
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `neoness` DEFAULT CHARACTER SET utf8mb4 ;
USE `neoness` ;

-- -----------------------------------------------------
-- Table `neoness`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `neoness`.`users` ;

CREATE TABLE IF NOT EXISTS `neoness`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(120) NULL DEFAULT NULL,
  `prenom` VARCHAR(120) NULL DEFAULT NULL,
  `pseudo` VARCHAR(120) NULL DEFAULT NULL,
  `email` VARCHAR(120) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `taille` DECIMAL(10,0) NULL DEFAULT NULL,
  `poids_depart` DECIMAL(10,0) NULL,
  `role` ENUM('admin', 'user') NOT NULL DEFAULT 'user',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `deleted_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `neoness`.`poids_quatidien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `neoness`.`poids_quatidien` ;

CREATE TABLE IF NOT EXISTS `neoness`.`poids_quatidien` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `poids` DECIMAL(10,0) NULL,
  `date_seance` DATE NULL,
  `temps_seance` TIME NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
